title: Neo
description: emmmmmmmm

social:
  - title: GitHub
    img: /EN-C.V/assets/images/github.ico
    url: https://github.com/nunchakus888
  - title: V2EX
    img: /EN-C.V/assets/images/v2ex.png
    url: https://www.v2ex.com/
  - title: Twitter
    img: /EN-C.V/assets/images/twitter.ico
    url: https://twitter.com/roidder
  - title: Gmail
    img: /EN-C.V/assets/images/gmail.png
    url: mailto:nunchakus2012@gmail.com

avatar: /EN-C.V/assets/images/github.ico
introduction: >
  emmmmmmmmmmmmm<br/>
  Neo Zhang<br/>
  Where there is a will, there is a way!

projects:
  title: Open Source Projects
  github:
    - xcatliu/mobi.css
    - xcatliu/typescript-tutorial
    - xcatliu/react-ie8
    - xcatliu/jekyllcn
    - xcatliu/leetcode
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/xcatliu">github.com/xcatliu</a>.</p>
    <p>If you love my projects, please <a href="https://github.com/xcatliu/buy-me-a-coffee">buy me a coffee</a> to support me.</p>

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Microsoft: Software Engineer II"
    - date: 2016-04
    - "Meituan: Senior Front-End Engineer"
    - date: 2015-04
    - "Meituan: Front-End Engineer"
    - date: 2013-06
    - "Meituan: Front-End Engineer Internship"
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: 2013-06
    - "Bachelor of WuHan University: Computer Science and Technology"
    - date: 2009-09

google_analytics: UA-45256157-13
